
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8076:80"
    depends_on:
      - appt
    container_name: todo_nginx

  appt:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
        - db
    container_name: todo_app

  db:
      image: postgres:latest
      restart: always
      volumes:
              - ./tmp/db:/var/lib/postgresql/data
      environment:
              POSTGRES_DB: laravel
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
      ports:
              - 8101:5432
      container_name: todo_db






